# Netlify Configuration for Brainrot Judge

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

# Development redirects (for local API testing)
[[redirects]]
  from = "/api/*"
  to = "https://brainrot-api.w4hf9yq226.workers.dev/api/:splat"
  status = 200
  force = false
  condition = "Role=visitor"